gestionarticles/urls.py
from django.urls import path

from . import views

app_name = 'gestionarticles'
urlpatterns = [
    path('articles', views.articles, name='articles'),
    path('ajouter_article', views.ajouter_article, name='ajouter_article'),
    path('modifier_article/(<id>[0-9]+)', views.modifier_article, name='modifier_article'),
    path('save_article/(<id>[0-9]+)', views.save_article, name='save_article'),
    path('delete_article/(<id>[0-9]+)', views.delete_article, name='delete_article'),
    path('affiche_commande_article/(<id>[0-9]+)', views.affiche_commande_article, name='affiche_commande_article'),
]

gestionstocks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestionauthentifications.urls')),
    path('gestionarticles/', include('gestionarticles.urls')),
    path('gestionclients/', include('gestionclients.urls')),
    path('gestionfournisseurs/', include('gestionfournisseurs.urls')),
    path('gestionauthentifications/', include('gestionauthentifications.urls')),
    path('gestioncommandes/', include('gestioncommandes.urls')),
    path('gestionpersonnels/', include('gestionpersonnels.urls')),
    path('gestionfactures/', include('gestionfactures.urls')),
    path('gestionlivraisons/', include('gestionlivraisons.urls')),
    path('gestionvehicules/', include('gestionvehicules.urls')),


#
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionarticles/models.py
from django.db import models
from gestionfournisseurs.models import Fournisseur

# Create your models here.


class Categorie(models.Model):
    id = models.AutoField(primary_key=True)
    libelle = models.CharField(max_length=30)

    class Meta:
        managed = True
        db_table = 'categorie'

    def __str__(self):
        return self.libelle


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    designation = models.CharField(max_length=50)
    quantite_stock = models.FloatField()
    prix_unitaire = models.FloatField()
    tva = models.FloatField()
    categorie = models.ForeignKey(Categorie, models.DO_NOTHING,null=True)
    fournisseur = models.ForeignKey(Fournisseur, models.DO_NOTHING,null=True)

    class Meta:
        managed = True
        db_table = 'article'

gestionarticles/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from gestionarticles.models import Article, Categorie
from gestionfournisseurs.models import Fournisseur
from gestioncommandes.models import Commande
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/gestionauthentifications/login')

def articles(request):
    articlelist = Article.objects.all()
    categorielist = Categorie.objects.all()
    fournisseurlist = Fournisseur.objects.all()
    return render(request, 'gestionarticles/articles.html', {'articlesMenu':'active','articlelist':articlelist,'categorielist':categorielist,
                                                             'fournisseurlist':fournisseurlist})
#
#
def ajouter_article(request):
    articlelist = Article.objects.all()
    designation = request.POST['designation']
    quantitestock = request.POST['quantitestock']
    prixunitaire = request.POST['prixunitaire']
    idcategorie = request.POST['categorie']
    tva = request.POST['tva']
    newtva = tva
    categorie = Categorie.objects.get(pk=idcategorie)
    idfournisseur=request.POST['fournisseur']
    fournisseur=Fournisseur.objects.get(pk=idfournisseur)
    if(Article.objects.filter(designation=designation).exists()):
        error_message = "Article existe déja"
        return render(request,'gestionarticles/articles.html',{'error_message':error_message,'articlelist':articlelist})
    else:
        a = Article(designation=designation,quantite_stock=quantitestock,
                    prix_unitaire=prixunitaire,tva=newtva,
                    categorie=categorie,fournisseur=fournisseur)
        a.save()
    return HttpResponseRedirect(reverse('gestionarticles:articles'))
#
#
def delete_article(request, id):
    a = Article.objects.get(pk=id)
    a.delete()
    return HttpResponseRedirect(reverse('gestionarticles:articles'))
#
#
def modifier_article(request, id):
    a = Article.objects.get(pk=id)
    articlelist = Article.objects.all()
    categorielist=Categorie.objects.all()
    fournisseurlist=Fournisseur.objects.all()
    context = {'articlesMenu':'active','article':a,
               'fournisseurlist':fournisseurlist,
               'articlelist':articlelist,'categorielist':categorielist}
    return render(request, 'gestionarticles/modifier_article.html', context)
#
#
def save_article(request, id):
    a = Article.objects.get(pk=id)
    if request.method == "POST":
        designation = request.POST['designation']
        quantitestock = request.POST['quantitestock']
        prixunitaire = request.POST['prixunitaire']
        idcategorie = request.POST['categorie']
        tva = request.POST['tva']
        newtva = tva
        categorie = Categorie.objects.get(pk=idcategorie)
        idfournisseur = request.POST['fournisseur']
        fournisseur = Fournisseur.objects.get(pk=idfournisseur)
        a.designation = designation
        a.quantite_stock = quantitestock
        a.prix_unitaire = prixunitaire
        a.tva = newtva
        a.categorie = categorie
        a.fournisseur = fournisseur
        a.save()
    return HttpResponseRedirect(reverse('gestionarticles:articles'))


def affiche_commande_article(request, id):
    commandelist = Commande.objects.filter(detailscommande__article__id=id)
    context = {'commandelist': commandelist, 'commandesMenu': 'active'}
    return render(request, 'gestioncommandes/commandes.html', context)

gestionarticles/templates/gestionarticles/article_base.html
{% extends 'genericfolder/base.html' %}
{% load static %}

{% block title %} Gestion des articles {% endblock %}

{% block contenu %}
<div class="row mt">
  {% if articlelist %}
    <div class="content-panel">
      <div class="adv-table">
        <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
          <thead>
            <tr>
              <th> #</th>
              <th> Désignation</th>
              <th> Quantité en stock</th>
              <th> Prix unitaire</th>
              <th> Catégorie</th>
              <th> TVA %</th>
              <th> Fournisseur </th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for a in articlelist %}
              <tr>
                <td> {{ forloop.counter }}</td>
                <td> {{ a.designation}}</td>
                <td> {{ a.quantite_stock }}</td>
                <td> {{ a.prix_unitaire }}</td>
                <td> {{ a.categorie }} </td>
                <td> {{ a.tva }}</td>
                <td> {{ a.fournisseur }}</td>

                <td>
                    <button  onclick="if(confirm('êtes-vous sûr de vouloir modifier cet article '+'{{a.nom}} {{a.designation}}'+' ?')){location.href='{% url 'gestionarticles:modifier_article' a.id %}'};"
                            class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>
                    </button>
                    <button onclick="if(confirm('êtes-vous sûr de vouloir supprimer cet article '+'{{a.nom}} {{a.designation}}'+' ?')){location.href='{% url 'gestionarticles:delete_article' a.id %}'};"
                            class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o "></i>
                    </button>
                     <button onclick="location.href='{% url 'gestionarticles:affiche_commande_article' a.id %}';"
                            class="btn btn-theme02 btn-xs">
                            <i class="fa fa-list-alt "> Commandes</i>
                     </button>

                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}

  <div class="col-lg-12">
    <h4><i class="fa fa-angle-right"></i> {% block subtitle %}{% endblock %}</h4>
    <div class="form-panel">
      {% if error_message %}
          <div style="color: red;" data-form-alert="" class="danger">
            {{error_message}}
          </div>
          <br>
      {% endif %}

      <form class="mbr-form" action="{% block form_action %}{% endblock %}" method="post"
            enctype="multipart/form-data" data-form-title="mobirise form"><input type="hidden" data-form-email="true">
        {% csrf_token %}
        <div class="row row-sm-offset">
            <div class="col-md-4 multi-horizontal" data-for="id_agence">
                <div class="form-group">
                    <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Désignation</label>
                    <input value="{{article.designation}}" type="text" class="form-control"
                           name="designation" data-form-field="name"
                           required id="designation">
                </div>
            </div>
            <div class="col-md-4 multi-horizontal" data-for="code_postale">
                <div class="form-group">
                    <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Quantité
                        en Stock</label>
                    <input value="{{article.quantite_stock}}" type="number" class="form-control"
                           name="quantitestock" data-form-field="name"
                           required="" id="quantitestock">
                </div>
            </div>
        </div>
        <div class="row row-sm-offset">
            <div class="col-md-4 multi-horizontal" data-for="nom">
                <div class="form-group">
                    <label class="form-control-label mbr-fonts-style display-7"
                           for="name-form1-2w">Prix unitaire </label>
                    <input value="{{article.prix_unitaire}}" type="text" class="form-control"
                           name="prixunitaire" data-form-field="name"
                           required="" id="prixunitaire">
                </div>
            </div>
            <div class="col-md-4 multi-horizontal" data-for="prenom">
                <div class="form-group">
                    <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Catégorie</label>
                    <select class="form-control" name="categorie">
                    <option selected="selected"> </option>

                        {% for categorie in categorielist %}
                         <option {% if categorie == article.categorie %}selected="selected" {% endif %}
                                value="{{ categorie.id  }}">{{ categorie.libelle}}
                        </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="row row-sm-offset">
          <div class="col-md-4 multi-horizontal" data-for="nom">
            <div class="form-group">
              <label class="form-control-label mbr-fonts-style display-7"
                    for="name-form1-2w">Fournisseur </label>
              <select class="form-control" name="fournisseur">
                <option selected="selected"></option>
                {% for fournisseur in fournisseurlist %}
                  <option {% if fournisseur == article.fournisseur %}selected="selected" {% endif %}
                         value="{{ fournisseur.id }}">{{ fournisseur.nom}}  {{ fournisseur.prenom}}
                  </option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="col-md-4 multi-horizontal" data-for="nom">
              <div class="form-group">
                  <label class="form-control-label mbr-fonts-style display-7"
                         for="name-form1-2w">T.V.A % </label>
                  <input value='{% widthratio article.tva 1 100 %}'  type="text" class="form-control"
                         name="tva" data-form-field="tva"
                         required="" id="tva">
              </div>
          </div>
        </div>
        <p align="left">
            <button type="submit" class="btn btn-primary btn-lg">{% block action_name %}{% endblock %}</button>
            <button type="reset" class="btn btn-default btn-lg">Annuler</button>
        </p>
      </form>
    </div>
    <!-- /form-panel -->
  </div>
</div>

{% endblock %}

gestionarticles/templates/gestionarticles/articles.html
{% extends 'gestionarticles/article_base.html' %}
{% load static %}

{% block subtitle %} Ajouter un article {% endblock %}

{% block form_action %}
    {% url 'gestionarticles:ajouter_article' %}
{% endblock %}

{% block action_name %}
    Ajouter
{% endblock %}

gestionarticles/templates/gestionarticles/modifier_article.html
{% extends 'gestionarticles/article_base.html' %}
{% load static %}

{% block subtitle %} Modifier l'article {{ article.designation }} {% endblock %}

{% block form_action %}
    {% url 'gestionarticles:save_article' article.id %}
{% endblock %}

{% block action_name %}
    Sauvegarder
{% endblock %}