gestionlivraisons/urls.py
from django.urls import path

from . import views

app_name = 'gestionlivraisons'
urlpatterns = [
    path('livraisons', views.livraisons, name='livraisons'),
    path('ajouter_livraison', views.ajouter_livraison, name='ajouter_livraison'),
    path('modifier_livraison/(<id>[0-9]+)', views.modifier_livraison, name='modifier_livraison'),
    path('save_livraison/(<id>[0-9]+)', views.save_livraison, name='save_livraison'),
    path('delete_livraison/(<id>[0-9]+)', views.delete_livraison, name='delete_livraison'),

]

gestionstocks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestionauthentifications.urls')),
    path('gestionarticles/', include('gestionarticles.urls')),
    path('gestionclients/', include('gestionclients.urls')),
    path('gestionfournisseurs/', include('gestionfournisseurs.urls')),
    path('gestionauthentifications/', include('gestionauthentifications.urls')),
    path('gestioncommandes/', include('gestioncommandes.urls')),
    path('gestionpersonnels/', include('gestionpersonnels.urls')),
    path('gestionfactures/', include('gestionfactures.urls')),
    path('gestionlivraisons/', include('gestionlivraisons.urls')),
    path('gestionvehicules/', include('gestionvehicules.urls')),


#
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionlivraisons/models.py
from django.db import models
from gestioncommandes.models import Commande,Personnel
from gestionvehicules.models import Vehicule


# Create your models here.


class Livraison(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateField()
    montant_total = models.FloatField()
    commande = models.ForeignKey(Commande, models.DO_NOTHING,null=True)
    vehicule = models.ForeignKey(Vehicule, models.DO_NOTHING,null=True)
    chauffeur = models.ForeignKey(Personnel, models.DO_NOTHING,null=True)

    def __str__(self):
            return self.commande.libelle
    class Meta:
        managed = True
        db_table = 'livraison'

gestionlivraisons/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.db import models
from django.contrib.auth.decorators import login_required
from gestionlivraisons.models import Livraison
from gestionvehicules.models import Vehicule
from gestioncommandes.models import Commande
from gestionpersonnels.models import Personnel


# Create your views here.


@login_required(login_url='/gestionauthentifications/login')

def livraisons(request):

    livraisonlist = Livraison.objects.all()
    vehiculelist = Vehicule.objects.all()
    commandelist = Commande.objects.all()
    personnellist = Personnel.objects.all()
    context = {'livraisonsMenu':'active','livraisontlist':livraisonlist,'vehiculelist':vehiculelist,
               'commandelist':commandelist,'personnellist':personnellist}
    return render(request, 'gestionlivraisons/livraisons.html', context)

def ajouter_livraison(request):
    date = request.POST['date']
    idcommande=request.POST['commande']
    commande=Commande.objects.get(pk=idcommande)
    idvehicule=request.POST['vehicule']
    vehicule=Vehicule.objects.get(pk=idvehicule)
    idchauffeur=request.POST['chauffeur']
    chauffeur=Personnel.objects.get(pk=idchauffeur)
    l = Livraison(date=date,commande=commande,vehicule=vehicule,chauffeur=chauffeur)
    l.save()
    return HttpResponseRedirect(reverse('gestionlivraisons:livraisons'))

def save_livraison(request, id):
    l = Livraison.objects.get(pk=id)
    if request.method == "POST":
        date = request.POST['date']
        montant_total = request.POST['montant_total']
        idcommande=request.POST['commande']
        commande=Commande.objects.get(pk=idcommande)
        idvehicule=request.POST['vehicule']
        vehicule=Vehicule.objects.get(pk=idvehicule)
        idchauffeur=request.POST['chauffeur']
        chauffeur=Personnel.objects.get(pk=idchauffeur)
        l.date = date
        l.montant_total = montant_total
        l.commande = commande
        l.vehicule = vehicule
        l.chauffeur = chauffeur
        l.save()
    return HttpResponseRedirect(reverse('gestionlivraisons:livraisons'))

def modifier_livraison(request, id):
    l = Livraison.objects.get(pk=id)
    livraisontlist = Livraison.objects.all()
    vehiculetlist = Vehicule.objects.all()
    commandelist=Commande.objects.all()
    personnellist=Personnel.objects.all()
    return render(request, 'gestionlivraisons/modifier_livraison.html', {'livraisonsMenu':'active', 'livraison':l,
                                                                         'livraisontlist':livraisontlist,'vehiculetlist':vehiculetlist,
                                                                         'commandelist':commandelist,'personnellist':personnellist})

def delete_livraison(request, id):
    l = Livraison.objects.get(pk=id)
    l.delete()
    return HttpResponseRedirect(reverse('gestionlivraisons:livraisons'))

gestionlivraisons/templates/gestionlivraisons/livraisons.html
{% extends 'gestionlivraisons/livraisons_base.html' %}
{% load static %}

{% block subtitle %} Ajouter une livraison {% endblock %}

{% block form_action %}
    {% url 'gestionlivraisons:ajouter_livraison' %}
{% endblock %}

{% block action_name %}
    Ajouter
{% endblock %}

gestionlivraisons/templates/gestionlivraisons/livraisons_base.html
{% extends 'genericfolder/base.html' %}
{% load static %}

{% block title %} Gestion des livraisons {% endblock %}

{% block contenu %}
<div class="row mt">
  {% if livraisonlist %}
    <div class="content-panel">
      <div class="adv-table">
        <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
          <thead>
            <tr>
                <th> #</th>
                <th> Date Livraison</th>
                <th> Chauffeur</th>
                <th> Véhicule</th>

              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for l in livraisonlist %}
            <tr>
                <td> {{ forloop.counter }}</td>
                <td> {{ l.date}}</td>
                <td> {{ l.chauffeur.nom }}{{ l.chauffeur.prenom }}</td>
                <td> {{ l.vehicule.matricule }}</td>

                <td>
                    <button onclick="if(confirm('êtes-vous sûr de vouloir modifier la livraison '+'{{l.id}} '+' ?'))location.href='{% url 'gestionlivraisons:modifier_livraison' l.id %}';"
                            class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>
                    </button>
                    <button onclick="if(confirm('êtes-vous sûr de vouloir supprimer la livraison '+'{{l.id}} '+' ?')){location.href='{% url 'gestionlivraisons:delete_livraison' l.id %}';"
                            class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o "></i>
                    </button>

                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}

  <div class="col-lg-12">
    <h4><i class="fa fa-angle-right"></i> {% block subtitle %}{% endblock %}</h4>
    <div class="form-panel">
      {% if error_message %}
      <div style="color: red;" data-form-alert="" class="danger">
        {{error_message}}
      </div>
      <br>
      {% endif %}

        <form class="mbr-form" action="{% block form_action %}{% endblock %}" method="post"
              enctype="multipart/form-data"
              data-form-title="mobirise form"><input type="hidden" data-form-email="true">
            {% csrf_token %}
            <div class="row row-sm-offset">
                <div class="col-md-4 multi-horizontal" data-for="id_agence">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7"
                               for="phone-form1-2w">Date livraison</label>
                      <input name="date" required class="form-control form-control-inline input-medium default-date-picker"
                                   value="{% if livraison.date %}{{ livraison.date|date:'Y-m-d' }}{% else %}{% now 'Y-m-d' %}{% endif %}"
                                   size="16" type="date" id="date">
                    </div>
                </div>
                <div class="col-md-4 multi-horizontal" data-for="code_postale">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Véhicule</label>
                        <select required class="form-control" name="vehicule">
                    <option></option>
                    {% for vehicule in vehiculelist %}
                        <option {% if vehicule == livraison.vehicule %}selected="selected" {%endif %}
                                value="{{ vehicule.id }}">{{vehicule.matricule}}
                        </option>
                    {% endfor %}
                </select>
                    </div>
                </div>
            </div>
            <div class="row row-sm-offset">
                <div class="col-md-8 multi-horizontal" data-for="nom">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7"
                               for="name-form1-2w">Commande </label>
                        <select class="form-control" name="commande">
                    <option selected="selected"> </option>

                        {% for commande in commandelist %}
                         <option {% if commande == livraison.commande %}selected="selected" {% endif %}
                                value="{{ commande.id }}">{{ commande.libelle}}
                        </option>
                        {% endfor %}
                    </select>
                    </div>
                </div>

            </div>
            <div class="row row-sm-offset">
                <div class="col-md-8 multi-horizontal" data-for="nom">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7"
                               for="name-form1-2w">Chauffeur </label>
                        <select class="form-control" name="chauffeur">
                            <option selected="selected"> </option>
                        {% for personnel in personnellist %}
                         <option {% if personnel == livraison.chauffeur %}selected="selected" {% endif %}
                                value="{{ personnel.id }}">{{ personnel.nom}}
                        </option>
                        {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <p align="left">
                <button type="submit" class="btn btn-primary btn-lg">{% block action_name %}{% endblock %}</button>
                <button type="reset" class="btn btn-default btn-lg">Annuler</button>
            </p>
        </form>
    </div>
      <!-- /form-panel -->
  </div>
</div>

{% endblock %}

gestionlivraisons/templates/gestionlivraisons/modifier_livraison.html
{% extends 'gestionlivraisons/livraisons_base.html' %}
{% load static %}

{% block subtitle %} Modifier la livraison {{livraison.id }}  {% endblock %}

{% block form_action %}
    {% url 'gestionlivraisons:save_livraison' livraison.id %}
{% endblock %}

{% block action_name %}
    Sauvegarder
{% endblock %}