gestionpersonnels/urls.py
from django.urls import path

from . import views

app_name = 'gestionpersonnels'
urlpatterns = [
    path('personnels', views.personnels, name='personnels'),
    path('ajouter_personnel', views.ajouter_personnel, name='ajouter_personnel'),
    path('modifier_personnel/(<id>[0-9]+)', views.modifier_personnel, name='modifier_personnel'),
    path('save_personnel/(<id>[0-9]+)', views.save_personnel, name='save_personnel'),
    path('delete_personnel/(<id>[0-9]+)', views.delete_personnel, name='delete_personnel'),
    path('change_password/(<id>[0-9]+)', views.change_password, name='change_password'),
    path('affiche_commande_personnel/(<id>[0-9]+)', views.affiche_commande_personnel, name='affiche_commande_personnel'),

]

gestionstocks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestionauthentifications.urls')),
    path('gestionarticles/', include('gestionarticles.urls')),
    path('gestionclients/', include('gestionclients.urls')),
    path('gestionfournisseurs/', include('gestionfournisseurs.urls')),
    path('gestionauthentifications/', include('gestionauthentifications.urls')),
    path('gestioncommandes/', include('gestioncommandes.urls')),
    path('gestionpersonnels/', include('gestionpersonnels.urls')),
    path('gestionfactures/', include('gestionfactures.urls')),
    path('gestionlivraisons/', include('gestionlivraisons.urls')),
    path('gestionvehicules/', include('gestionvehicules.urls')),


#
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionpersonnels/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Service(models.Model):
    id = models.AutoField(primary_key=True)
    intitule = models.CharField(max_length=30)
    nom_responsable = models.CharField(max_length=20)
    prenom_responsable = models.CharField(max_length=20)

    class Meta:
        managed = True
        db_table = 'service'


class Personnel(models.Model):
    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=20)
    prenom = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    service = models.ForeignKey(Service, models.DO_NOTHING,null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)
    is_admin = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'personnel'

gestionpersonnels/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from gestionauthentifications.models import UserRole, Role
from gestionpersonnels.models import Personnel, Service
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from gestioncommandes.models import Commande
# Create your views here.


@login_required(login_url='/gestionauthentifications/login')
def personnels(request):
    personnellist = Personnel.objects.all()
    servicelist=Service.objects.all()
    context = {'gestionPersonnelsMenu':'active','personnelsMenu':'active',
               'personnellist': personnellist,'servicelist':servicelist}
    return render(request, 'gestionpersonnels/personnels.html', context)


def ajouter_personnel(request):
    nom = request.POST['nom']
    prenom = request.POST['prenom']
    pseudo = request.POST['pseudo']
    password = request.POST['password']
    email = request.POST['email']
    idservice = request.POST['service']
    if request.POST.get("isadmin") == "checked":
        isadmin = True
    else:
        isadmin = False
    print(isadmin)
    service = Service.objects.get(pk=idservice)
    if(not User.objects.filter(username=pseudo)):
        user = User.objects.create_user(username=pseudo, password=password)
        print(user)
        p = Personnel(nom=nom,prenom=prenom,email=email,service=service,
                      user=user,
                      is_admin=isadmin)
        p.save()
    return HttpResponseRedirect(reverse('gestionpersonnels:personnels'))
#
#
def delete_personnel(request, id):
    p = Personnel.objects.get(pk=id)
    p.user.delete()
    p.delete()
    return HttpResponseRedirect(reverse('gestionpersonnels:personnels'))
#
#
def modifier_personnel(request, id):
    p = Personnel.objects.get(pk=id)
    personnellist = Personnel.objects.all()
    servicelist=Service.objects.all()
    context = {'personnelsMenu':'active','personnel':p,
               'personnellist':personnellist,'servicelist':servicelist}
    return render(request, 'gestionpersonnels/modifier_personnel.html', context)
#
def save_personnel(request, id):
    p = Personnel.objects.get(pk=id)
    user = p.user
    if request.method == "POST":
        nom = request.POST['nom']
        prenom = request.POST['prenom']
        pseudo = request.POST['pseudo']
        email = request.POST['email']
        idservice = request.POST['service']
        service = Service.objects.get(pk=idservice)
        p.nom = nom
        p.prenom = prenom
        p.email = email
        p.service = service
        if request.POST.get("isadmin") == "checked":
            isadmin = True
        else:
            isadmin = False
        p.is_admin = isadmin
        user.username = pseudo
        p.save()
        user.save()
    return HttpResponseRedirect(reverse('gestionpersonnels:personnels'))


def change_password(request, id):
    personnel = Personnel.objects.get(pk=id)
    context = {"personnel": personnel, 'personnelsMenu':'active'}
    if request.method == "POST":
        old_password = request.POST['oldPassword']
        new_password = request.POST['newPassword']
        confirm_new_password = request.POST['confirmNewPassword']
        error_message = ""
        success_message = ""
        if old_password and new_password and confirm_new_password:
            user = authenticate(username=personnel.user.username, password=old_password)
            if user:
                if new_password == confirm_new_password:
                    personnel.user.set_password(new_password)
                    personnel.user.save()
                    success_message = "Mot de passe changé avec succès"
                else:
                    error_message = "Faut confirmer avec le même mot de passe"
            else:
                error_message = "Mot de passe incorrect"
        else:
            error_message = "Il faut remplir tous les champs"
        context.update({"error_message": error_message, "success_message": success_message})
    return render(request, 'gestionpersonnels/change_password.html', context)


def affiche_commande_personnel(request,id):
    commandelist = Commande.objects.filter(personnel__id=id)
    context={"commandelist": commandelist, 'commandesMenu': 'active'}
    return render(request,'gestioncommandes/commandes.html', context)

gestionpersonnels/templates/gestionpersonnels/change_password.html
{% extends 'genericfolder/base.html' %}
{% load static %}

{% block title %} {{personnel.prenom}} {{personnel.nom}} {% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css"
      href="{% static 'genericfolder/lib/bootstrap-fileupload/bootstrap-fileupload.css' %}"/>
{% endblock %}

{% block contenu %}
    <div class="row mt">
          <div class="col-lg-12">
            <div class="form-panel">
              <h4 class="mb">Changer mot de passe</h4>
              {% if error_message %}
                <div class="alert alert-danger">
                  {{ error_message }}
                </div>
              {% endif %}
              {% if success_message %}
                <div class="alert alert-success">
                  {{ success_message }}
                </div>
              {% endif %}

              <form action="{% url 'gestionpersonnels:change_password' personnel.id %}" class="form-horizontal style-form" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label class="col-sm-2 col-sm-2 control-label">Ancienne mot de passe</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control" name="oldPassword">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-2 col-sm-2 control-label">Nouvelle mot de passe</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control" name="newPassword">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-2 col-sm-2 control-label">Confirmer le mot de passe</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control" name="confirmNewPassword">
                  </div>
                </div>
                <p align="left">
                    <button type="submit" class="btn btn-primary btn-lg">Sauvgarder</button>
                    <button type="reset" class="btn btn-default btn-lg">Annuler</button>
                </p>
              </form>
            </div>
          </div>
          <!-- col-lg-12-->
        </div>
{% endblock %}

gestionpersonnels/templates/gestionpersonnels/modifier_personnel.html
{% extends 'gestionpersonnels/personnels_base.html' %}
{% load static %}

{% block subtitle %} Modifier le personnel: {{personnel.prenom }} {{ personnel.nom }} {% endblock %}

{% block form_action %}
    {% url 'gestionpersonnels:save_personnel' personnel.id %}
{% endblock %}

{% block action_name %}
    Sauvegarder
{% endblock %}

gestionpersonnels/templates/gestionpersonnels/personnels.html
{% extends 'gestionpersonnels/personnels_base.html' %}
{% load static %}

{% block subtitle %} Ajouter un personnel {% endblock %}

{% block form_action %}
    {% url 'gestionpersonnels:ajouter_personnel' %}
{% endblock %}

{% block action_name %}
    Ajouter
{% endblock %}

gestionpersonnels/templates/gestionpersonnels/personnels_base.html
{% extends 'genericfolder/base.html' %}
{% load static %}

{% block title %} Gestion des personnels {% endblock %}

{% block contenu %}
<div class="row mt">
  {% if personnellist %}
    <div class="content-panel">
      <div class="adv-table">
        <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
          <thead>
            <tr>
                <th> #</th>
                <th> Nom</th>
                <th> Prénom</th>
                 <th> Email</th>
                <th> Service</th>
                <th> Admin?</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for p in personnellist %}
            <tr>
                <td> {{ forloop.counter }}</td>
                <td> {{ p.nom}}</td>
                <td> {{ p.prenom}}</td>
                 <td> {{ p.email }}</td>
                <td> {{ p.service.intitule }}</td>
                <td> {{ p.is_admin }}</td>


                <td>
                    <button onclick="if(confirm('êtes-vous sûr de vouloir modifier le personnel '+'{{p.nom}} {{p.prenom}}'+' ?')){location.href='{% url 'gestionpersonnels:modifier_personnel' p.id %}'};"
                            class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>
                    </button>
                    <button onclick="if(confirm('êtes-vous sûr de vouloir supprimer le personnel '+'{{p.nom}} {{p.prenom}}'+' ?')){location.href='{% url 'gestionpersonnels:delete_personnel' p.id %}'};"
                            class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o "></i>
                    </button>
                    <button onclick="location.href='{% url 'gestionpersonnels:change_password' p.id %}';"
                            class="btn btn-warning btn-xs"><i class="fa fa-lock"></i>
                    </button>
                      <button onclick="location.href='{% url 'gestionpersonnels:affiche_commande_personnel' p.id %}';"
                            class="btn btn-theme02 btn-xs">
                     <i class="fa fa-list-alt "> Commandes</i>
                      </button>
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}

  <div class="col-lg-12">
    <h4><i class="fa fa-angle-right"></i> {% block subtitle %}{% endblock %}</h4>
    <div class="form-panel">
      {% if error_message %}
      <div style="color: red;" data-form-alert="" class="danger">
        {{error_message}}
      </div>
      <br>
      {% endif %}

        <form class="mbr-form" action="{% block form_action %}{% endblock %}" method="post"
              enctype="multipart/form-data"
              data-form-title="mobirise form"><input type="hidden" data-form-email="true">
            {% csrf_token %}

            <div class="row row-sm-offset">
                <div class="col-md-4 multi-horizontal" data-for="id_agence">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7"
                               for="phone-form1-2w">Nom</label>
                        <input value="{{personnel.nom}}" type="text" class="form-control"
                               name="nom" data-form-field="name"
                               required="" id="nom">
                    </div>
                </div>
                <div class="col-md-4 multi-horizontal" data-for="code_postale">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Prénom</label>
                        <input value="{{personnel.prenom}}" type="text" class="form-control"
                               name="prenom" data-form-field="name"
                               required="" id="prenom">
                    </div>
                </div>
            </div>

            <div class="row row-sm-offset">
                <div class="col-md-4 multi-horizontal" data-for="id_agence">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7"
                               for="phone-form1-2w">Email</label>
                        <input value="{{personnel.email}}" type="text" class="form-control"
                               name="email" data-form-field="name"
                               required="" id="email">
                    </div>
                </div>
                <div class="col-md-4 multi-horizontal" data-for="code_postale">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Service</label>
                        <select class="form-control" name="service">
                            <option selected="selected"> </option>

                            {% for service in servicelist %}
                                <option {% if service == personnel.service %}selected="selected" {% endif %}
                                        value="{{ service.id }}">{{ service.intitule}}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="row row-sm-offset">
                <div class="col-md-4 multi-horizontal" data-for="email">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7" for="email-form1-2w">Pseudo</label>
                        <input value="{{personnel.user.username}}" type="tel" class="form-control"
                               name="pseudo" data-form-field="tel"
                               required id="pseudo">
                    </div>
                </div>
                {% if not personnel %}
                    <div class="col-md-4 multi-horizontal" data-for="phone">
                        <div class="form-group">
                            <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Mot
                                de passe</label>
                            <input value="{{personnel.motdepasse}}" type="password" class="form-control"
                                   name="password" data-form-field="phone"
                                   required id="motdepasse">
                        </div>
                    </div>
                {% endif %}
            </div>

            <div class="checkbox">
                <label>
                    <input {% if personnel.is_admin %}checked{% endif %} name="isadmin" type="checkbox" value="checked">
                        Admin?
                </label>
            </div>

            <p align="left">
                <button type="submit" class="btn btn-primary btn-lg">{% block action_name %}{% endblock %}</button>
                <button type="reset" class="btn btn-default btn-lg">Annuler</button>
            </p>
        </form>
    </div>
    <!-- /form-panel -->
  </div>
</div>

{% endblock %}