gestionclients/urls.py
from django.urls import path

from . import views

app_name = 'gestionclients'
urlpatterns = [
    path('clients', views.clients, name='clients'),
    path('ajouter_client', views.ajouter_client, name='ajouter_client'),
    path('modifier_client/(<id>[0-9]+)', views.modifier_client, name='modifier_client'),
    path('save_client/(<id>[0-9]+)', views.save_client, name='save_client'),
    path('delete_client/(<id>[0-9]+)', views.delete_client, name='delete_client'),
    path('affiche_commande_client/(<id>[0-9]+)', views.affiche_commande_client, name='affiche_commande_client'),

]

gestionstocks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestionauthentifications.urls')),
    path('gestionarticles/', include('gestionarticles.urls')),
    path('gestionclients/', include('gestionclients.urls')),
    path('gestionfournisseurs/', include('gestionfournisseurs.urls')),
    path('gestionauthentifications/', include('gestionauthentifications.urls')),
    path('gestioncommandes/', include('gestioncommandes.urls')),
    path('gestionpersonnels/', include('gestionpersonnels.urls')),
    path('gestionfactures/', include('gestionfactures.urls')),
    path('gestionlivraisons/', include('gestionlivraisons.urls')),
    path('gestionvehicules/', include('gestionvehicules.urls')),


#
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionclients/models.py
from django.db import models

# Create your models here.


class Client(models.Model):
    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=20)
    prenom = models.CharField(max_length=20)
    adresse = models.CharField(max_length=50)
    telephone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'client'

    def __str__(self):
        return self.prenom + " " + self.nom

gestionclients/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.db import models
from gestionclients.models import Client
from gestioncommandes.models import Commande
from django.contrib.auth.decorators import login_required

# Create your views here.
# from generic_app.models import Agence, Assure

@login_required(login_url='/gestionauthentifications/login')
def clients(request):

    clientlist = Client.objects.all()
    context = {'clientsMenu':'active', 'clientlist':clientlist}
    return render(request, 'gestionclients/clients.html', context)

#
def ajouter_client(request):
    nomclient = request.POST['nom']
    prenomclient = request.POST['prenom']
    adresseclient = request.POST['adresse']
    emailclient = request.POST['email']
    telephoneclient = request.POST['telephone']
    clientlist=Client.objects.all()
    if (Client.objects.filter(email=emailclient).exists()):
        error_message = "Client existe déja"
        return render(request,'gestionclients/clients.html',{'error_message':error_message,'clientlist':clientlist})
    else:
        c = Client (nom=nomclient,prenom=prenomclient,adresse=adresseclient,email=emailclient,telephone=telephoneclient)
        c.save()
    return HttpResponseRedirect(reverse('gestionclients:clients'))

def modifier_client(request, id):
    c = Client.objects.get(pk=id)
    clientlist = Client.objects.all()
    return render(request, 'gestionclients/modifier_client.html', {'clientsMenu':'active', 'client':c, 'clientlist':clientlist})

def delete_client(request, id):
    c = Client.objects.get(pk=id)
    c.delete()
    return HttpResponseRedirect(reverse('gestionclients:clients'))

def save_client(request, id):
    c = Client.objects.get(pk=id)
    if request.method == "POST":
        nomclient = request.POST['nom']
        prenomclient = request.POST['prenom']
        adresseclient = request.POST['adresse']
        emailclient = request.POST['email']
        telephoneclient= request.POST['telephone']
        c.nom = nomclient
        c.prenom = prenomclient
        c.adresse = adresseclient
        c.email = emailclient
        c.telephone = telephoneclient
        c.save()
    return HttpResponseRedirect(reverse('gestionclients:clients'))


def affiche_commande_client (request, id):
    commandelist = Commande.objects.filter(client__id=id)
    context = {'commandelist':commandelist}
    return render(request, 'gestioncommandes/commandes.html',context)

gestionclients/templates/gestionclients/clients.html
{% extends 'gestionclients/clients_base.html' %}
{% load static %}

{% block subtitle %} Ajouter un client {% endblock %}

{% block form_action %}
    {% url 'gestionclients:ajouter_client' %}
{% endblock %}

{% block action_name %}
    Ajouter
{% endblock %}

gestionclients/templates/gestionclients/clients_base.html
{% extends 'genericfolder/base.html' %}
{% load static %}

{% block title %} Gestion des clients {% endblock %}

{% block contenu %}
<div class="row mt">
  {% if clientlist %}
    <div class="content-panel">
      <div class="adv-table">
        <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
          <thead>
            <tr>
                <th> #</th>
                <th> Nom</th>
                <th> Prenom</th>
                <th> Adresse</th>
                <th> Téléphone</th>
                <th> Email</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for c in clientlist %}
            <tr>
                <td> {{ forloop.counter }}</td>
                <td> {{ c.nom}}</td>
                <td> {{ c.prenom }}</td>
                <td> {{ c.adresse }}</td>
                <td> {{ c.telephone }}</td>
                <td> {{ c.email }}</td>
                <td>
                    <button onclick="if(confirm('êtes-vous sûr de vouloir modifier le client '+'{{c.nom}} {{c.prenom}}'+' ?'))location.href='{% url 'gestionclients:modifier_client' c.id %}';"
                            class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>
                    </button>
                    <button onclick="if(confirm('êtes-vous sûr de vouloir supprimer le client '+'{{c.nom}} {{c.prenom}}'+' ?')){location.href='{% url 'gestionclients:delete_client' c.id %}'};"
                            class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o "></i>
                    </button>
                      <button onclick="if(confirm('êtes-vous sûr de vouloir afficher les commandes du client '+'{{c.nom}}'+' {{c.prenom}} ?')){location.href='{% url 'gestionclients:affiche_commande_client' c.id %}'};"
                            class="btn btn-theme02 btn-xs">
                     <i class="fa fa-list-alt "> Commande</i>
                      </button>
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}

  <div class="col-lg-12">
    <h4><i class="fa fa-angle-right"></i> {% block subtitle %}{% endblock %}</h4>
    <div class="form-panel">
      {% if error_message %}
      <div style="color: red;" data-form-alert="" class="danger">
        {{error_message}}
      </div>
      <br>
      {% endif %}

        <form class="mbr-form" action="{% block form_action %}{% endblock %}" method="post"
              enctype="multipart/form-data"
              data-form-title="mobirise form"><input type="hidden" data-form-email="true">
            {% csrf_token %}
            <div class="row row-sm-offset">
                <div class="col-md-4 multi-horizontal" data-for="id_agence">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7"
                               for="phone-form1-2w">Nom</label>
                        <input value="{{client.nom}}" type="text" class="form-control"
                               name="nom" data-form-field="name"
                               required="" id="nomclient">
                    </div>
                </div>
                <div class="col-md-4 multi-horizontal" data-for="code_postale">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Prénom</label>
                        <input value ="{{client.nom}}" type="text" class="form-control"
                               name="prenom" data-form-field="name"
                               required="" id="prenomclient">
                    </div>
                </div>
            </div>
            <div class="row row-sm-offset">
                <div class="col-md-8 multi-horizontal" data-for="nom">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7"
                               for="name-form1-2w">Adresse </label>
                        <input value ="{{client.adresse}}" type="text" class="form-control"
                               name="adresse" data-form-field="name"
                               required="" id="adresseclient">
                    </div>
                </div>

            </div>
            <div class="row row-sm-offset">
                <div class="col-md-4 multi-horizontal" data-for="telephone">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7" for="email-form1-2w">Téléphone</label>
                        <input value ="{{client.telephone}}" type="telephone" class="form-control"
                               name="telephone" data-form-field="telephone"
                               required id="telephoneclient">
                    </div>
                </div>
                <div class="col-md-4 multi-horizontal" data-for="phone">
                    <div class="form-group">
                        <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-2w">Email</label>
                        <input value="{{client.email}}" type="tel" class="form-control"
                               name="email" data-form-field="phone"
                               required id="emailclient">
                    </div>
                </div>
            </div>

            <p align="left">
                <button type="submit" class="btn btn-primary btn-lg">{% block action_name %}{% endblock %}</button>
                <button type="reset" class="btn btn-default btn-lg">Annuler</button>
            </p>
        </form>
    </div>
      <!-- /form-panel -->
  </div>
</div>

{% endblock %}

gestionclients/templates/gestionclients/modifier_client.html
{% extends 'gestionclients/clients_base.html' %}
{% load static %}

{% block subtitle %} Modifier le client {{client.prenom }} {{ client.nom }} {% endblock %}

{% block form_action %}
    {% url 'gestionclients:save_client' client.id %}
{% endblock %}

{% block action_name %}
    Sauvegarder
{% endblock %}